### ISSUE TITLE
Allow for missing data

### ISSUE THREAD

**Issue by miracle2k** [jelz/cf-graphql#5] opened 2017-04-19 17:48 UTC
Another problem I had: If I add a new field to an existing content type that is "required", loading older documents that were still lacking this field raises an exception (I believe the exception came from the graphql library on the server).

My temporary fix for now is this:

https://github.com/miracle2k/cf-graphql/commit/ea6333a38abd0370b4d64ce621b98e7fa67c6729

A real one would probably need to account for different datatypes.

It seems to me this kind of content-model upgrade process, where a newly "required" field is not filled in every document yet, should be supported.

**Comment by jelz** [comment] 2017-04-23 16:51
I've just released v0.2. This commit https://github.com/jelz/cf-graphql/commit/db80568a0c55f6446e6a7572ce8251962ae44c95 should fix the problem. The only thing I did is to remove non-nullability markers from required fields.

Official documentation for [`GraphQLNonNull`](http://graphql.org/graphql-js/type/#graphqlnonnull) states:

> It is useful for fields which you can make a strong guarantee on non-nullability, for example usually the id field of a database row will never be null.

As your example shows we don't have this strong guarantee.

Could you please install v0.2 and tell me if the problem is gone?

**Comment by jelz** [comment] 2017-05-03 12:33
Checked again, works fine in v0.3. Closing.

**Closed by jelz** 2017-05-03 12:33 UTC
